### ISSUE TITLE
documetnation needed for KEGG data

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_dev_seed#31]
https://github.com/statonlab/tripal_dev_mini_dataset/tree/master/kegg_annotations

**Comment by bradfordcondon** [comment]
pinging @jwest60 .  Any questions about this?

**Comment by jwest60** [comment]
apologies for the late response on this

i just finished writing the documentation and created a [pr](https://github.com/statonlab/tripal_dev_seed/pull/52). if you need me to add another section or change anything up let me know and i'll get right on it

**Comment by bradfordcondon** [comment]
thanks @jwest60
