### ISSUE TITLE
Where do I get the FASTA files?

### ISSUE THREAD

**Issue by cricha59** [statonlab/tripal_dev_seed#61]
The RTD guide does not tell me where to get the FASTA file.

**Comment by bradfordcondon** [comment]
hi @cricha59 :

all files are avialable here:

https://github.com/statonlab/tripal_dev_seed/tree/master/Fexcel_mini

A list of what data is located where is here:

https://github.com/statonlab/tripal_dev_seed#file-description

You are right this info needs to be migrated to the readthedocs guide, thanks!

**Comment by bradfordcondon** [comment]
updated the front page of guide to link to the file location, thanks.
