### ISSUE TITLE
fasta loader requires regexp

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_dev_seed#63]
* Do otehr loaders allow type specification without regexp?  If so, fix FASTA importer
* If not, modify devseed instructions with working regexp ie (`>(.*?)`)

**Comment by jwest60** [comment]
corrected regexp: `>(.*)`

**Comment by bradfordcondon** [comment]
The InterPro importer doesnt require a regexp to link to the parent.  I think this is something that shouldnt be required of hte FASTA importer, ie, it should look for parent feature with the same name like hte other importers do.

**Comment by bradfordcondon** [comment]
https://github.com/tripal/tripal/issues/676

I created an issue.  Let's leave it as is for now and see if we can remove the re requirement, as it isnt required for other loaders.

**Comment by bradfordcondon** [comment]
i added the `>(.*)` regexp to the fasta loader guide.  I wish it wasnt necessary but thats an issue for core to decide.
